name: Auto  merge
on: pull_request
jobs:
    merge:
        if: ${{ github.actor == 'dependabot[bot]' }} # DependabotのPRのみ
        runs-on: ubuntu-latest
        permissions:
            contents: write # PRの更新権限を付与
            pull-requests: write
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub CLIのクレデンシャル
        steps:
            - uses: actions/checkout@v4
            - run: |
                gh pr review "${GITHUB_HEAD_REF}" --approve
                gh pr merge "${GITHUB_HEAD_REF}" --merge --auto