name: GITHUB_OUTPUT
on: push
jobs:
    share:
        runs-on: ubuntu-latest
        steps:
            - id: source # ステップIDを指定
              run: echo "result=Hello" >> "${GITHUB_OUTPUT}" # GITHUB_OUTPUTに出力を設定
            - env:
                RESULT: ${{ steps.source.outputs.result }} # stepsコンテキストから参照
              run: echo "${RESULT}"