name: Hello # ワークフロー名
on: push
jobs:
    hello: # ジョブID
        runs-on: ubuntu-latest # ランナー（Ubuntuで実行）
        steps: # ステップの定義
            - run: echo "Hello, World" # シェルコマンド実行
            - uses: actions/checkout@v6 # アクションの呼び出し