name: Conditions
on: push
jobs:
    skip-or-run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello"
              if: ${{ contains(github.run_id, '1') }} # ワークフロー実行IDに'1'が含まれる場合に実行